server:
  port: 8553
spring:
  ## 数据库配置 - start
  datasource:
    url: jdbc:mysql://39.106.29.131:3306/blog?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: 102030.ainiA
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置
    druid:
      # 初始化连接数大小
      initial-size: 5
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 10
      # 连接超时时间
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
  mvc:
    favicon:
      enabled: false
mybatis:
  mapperLocations: classpath:mapper/**/*Mapper.xml
  #  config-location: classpath:mybatis-config.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql